import type { StorageClass } from '@/lib/trgs510/types';

export const STORAGE_CLASSES: StorageClass[] = [
  {
    id: '1',
    label: 'LGK 1',
    shortDescription: 'Explosive Stoffe',
    searchTerms: ['explosiv', 'sprengstoff', 'explosive stoffe'],
  },
  {
    id: '2 A',
    label: 'LGK 2 A',
    shortDescription: 'Gase',
    searchTerms: ['gase', 'druckgas', 'gasflaschen'],
  },
  {
    id: '2 B',
    label: 'LGK 2 B',
    shortDescription: 'Aerosolpackungen',
    searchTerms: ['aerosole', 'spraydosen', 'aerosolpackungen'],
  },
  {
    id: '3',
    label: 'LGK 3',
    shortDescription: 'Entzündbare flüssige Stoffe',
    searchTerms: ['entzündbare flüssigkeiten', 'lösemittel', 'brennbare flüssigkeiten'],
  },
  {
    id: '4.1 A',
    label: 'LGK 4.1 A',
    shortDescription: 'Sonstige explosionsgefährliche Stoffe',
    searchTerms: ['explosionsgefährlich', 'sonstige explosionsgefährliche stoffe'],
  },
  {
    id: '4.1 B',
    label: 'LGK 4.1 B',
    shortDescription: 'Entzündbare feste oder desensibilisierte Stoffe',
    searchTerms: ['entzündbare feststoffe', 'desensibilisierte explosive stoffe'],
  },
  {
    id: '4.2',
    label: 'LGK 4.2',
    shortDescription: 'Pyrophore oder selbsterhitzungsfähige Stoffe',
    searchTerms: ['selbstentzündlich', 'pyrophor', 'selbsterhitzend'],
  },
  {
    id: '4.3',
    label: 'LGK 4.3',
    shortDescription: 'Stoffe, die mit Wasser entzündliche Gase bilden',
    searchTerms: ['wasserreaktiv', 'wasser entzündliche gase', 'calciumcarbid'],
  },
  {
    id: '5.1 A',
    label: 'LGK 5.1 A',
    shortDescription: 'Stark oxidierend wirkende Stoffe',
    searchTerms: ['stark oxidierend', 'brandfördernd'],
  },
  {
    id: '5.1 B',
    label: 'LGK 5.1 B',
    shortDescription: 'Oxidierend wirkende Stoffe',
    searchTerms: ['oxidierend', 'brandfördernd'],
  },
  {
    id: '5.1 C',
    label: 'LGK 5.1 C',
    shortDescription: 'Ammoniumnitrat und ammoniumnitrathaltige Stoffe',
    searchTerms: ['ammoniumnitrat', 'trgs 511'],
  },
  {
    id: '5.2',
    label: 'LGK 5.2',
    shortDescription: 'Organische Peroxide und selbstzersetzliche Stoffe',
    searchTerms: ['organische peroxide', 'selbstzersetzlich', 'peroxide'],
  },
  {
    id: '6.1 A',
    label: 'LGK 6.1 A',
    shortDescription: 'Brennbare akut toxische Stoffe',
    searchTerms: ['akut toxisch brennbar', 'giftig brennbar'],
  },
  {
    id: '6.1 B',
    label: 'LGK 6.1 B',
    shortDescription: 'Nichtbrennbare akut toxische Stoffe',
    searchTerms: ['akut toxisch nichtbrennbar', 'giftig nichtbrennbar'],
  },
  {
    id: '6.1 C',
    label: 'LGK 6.1 C',
    shortDescription: 'Brennbare toxische oder chronisch wirkende Stoffe',
    searchTerms: ['chronisch toxisch brennbar', 'giftig chronisch brennbar'],
  },
  {
    id: '6.1 D',
    label: 'LGK 6.1 D',
    shortDescription: 'Nichtbrennbare toxische oder chronisch wirkende Stoffe',
    searchTerms: ['chronisch toxisch nichtbrennbar', 'giftig chronisch nichtbrennbar'],
  },
  {
    id: '6.2',
    label: 'LGK 6.2',
    shortDescription: 'Ansteckungsgefährliche Stoffe',
    searchTerms: ['infektiös', 'ansteckungsgefährlich', 'biologisch'],
  },
  {
    id: '7',
    label: 'LGK 7',
    shortDescription: 'Radioaktive Stoffe',
    searchTerms: ['radioaktiv', 'strahlenschutz'],
  },
  {
    id: '8 A',
    label: 'LGK 8 A',
    shortDescription: 'Brennbare ätzende Stoffe',
    searchTerms: ['ätzend brennbar', 'säuren brennbar', 'laugen brennbar'],
  },
  {
    id: '8 B',
    label: 'LGK 8 B',
    shortDescription: 'Nichtbrennbare ätzende Stoffe',
    searchTerms: ['ätzend nichtbrennbar', 'säuren nichtbrennbar', 'laugen nichtbrennbar'],
  },
  {
    id: '10-13',
    label: 'LGK 10-13',
    shortDescription: 'Sonstige brennbare und nichtbrennbare Stoffe',
    searchTerms: ['sonstige stoffe', 'lagerklasse 10 bis 13'],
  },
  {
    id: '10*',
    label: 'LGK 10*',
    shortDescription: 'Brennbare Flüssigkeiten, soweit nicht LGK 3',
    searchTerms: ['brennbare flüssigkeiten', 'nicht lgk 3'],
  },
  {
    id: '11*',
    label: 'LGK 11*',
    shortDescription: 'Brennbare Feststoffe',
    searchTerms: ['brennbare feststoffe'],
  },
  {
    id: '12*',
    label: 'LGK 12*',
    shortDescription: 'Nichtbrennbare Flüssigkeiten',
    searchTerms: ['nichtbrennbare flüssigkeiten'],
  },
  {
    id: '13*',
    label: 'LGK 13*',
    shortDescription: 'Nichtbrennbare Feststoffe',
    searchTerms: ['nichtbrennbare feststoffe'],
  },
] as const satisfies StorageClass[];
