import type { StorageClass } from '@/lib/trgs510/types';

export const STORAGE_CLASSES: StorageClass[] = [
  {
    id: '1',
    label: 'LGK 1',
    shortDescription: 'Explosive Stoffe',
    searchTerms: ['explosiv', 'sprengstoff', 'explosive stoffe'],
  },
  {
    id: '2 A',
    label: 'LGK 2 A',
    shortDescription: 'Gase',
    searchTerms: ['gase', 'druckgas', 'gasflaschen'],
  },
  {
    id: '2 B',
    label: 'LGK 2 B',
    shortDescription: 'Aerosolpackungen',
    searchTerms: ['aerosole', 'spraydosen', 'aerosolpackungen'],
  },
  {
    id: '3',
    label: 'LGK 3',
    shortDescription: 'EntzündBetriebsanweisungre flüssige Stoffe',
    searchTerms: ['entzündBetriebsanweisungre flüssigkeiten', 'lösemittel', 'brennBetriebsanweisungre flüssigkeiten'],
  },
  {
    id: '4.1 A',
    label: 'LGK 4.1 A',
    shortDescription: 'Sonstige explosionsgefährliche Stoffe',
    searchTerms: ['explosionsgefährlich', 'sonstige explosionsgefährliche stoffe'],
  },
  {
    id: '4.1 B',
    label: 'LGK 4.1 B',
    shortDescription: 'EntzündBetriebsanweisungre feste oder desensibilisierte Stoffe',
    searchTerms: ['entzündBetriebsanweisungre feststoffe', 'desensibilisierte explosive stoffe'],
  },
  {
    id: '4.2',
    label: 'LGK 4.2',
    shortDescription: 'Pyrophore oder selbsterhitzungsfähige Stoffe',
    searchTerms: ['selbstentzündlich', 'pyrophor', 'selbsterhitzend'],
  },
  {
    id: '4.3',
    label: 'LGK 4.3',
    shortDescription: 'Stoffe, die mit Wasser entzündliche Gase bilden',
    searchTerms: ['wasserreaktiv', 'wasser entzündliche gase', 'calciumcarbid'],
  },
  {
    id: '5.1 A',
    label: 'LGK 5.1 A',
    shortDescription: 'Stark oxidierend wirkende Stoffe',
    searchTerms: ['stark oxidierend', 'brandfördernd'],
  },
  {
    id: '5.1 B',
    label: 'LGK 5.1 B',
    shortDescription: 'Oxidierend wirkende Stoffe',
    searchTerms: ['oxidierend', 'brandfördernd'],
  },
  {
    id: '5.1 C',
    label: 'LGK 5.1 C',
    shortDescription: 'Ammoniumnitrat und ammoniumnitrathaltige Stoffe',
    searchTerms: ['ammoniumnitrat', 'trgs 511'],
  },
  {
    id: '5.2',
    label: 'LGK 5.2',
    shortDescription: 'Organische Peroxide und selbstzersetzliche Stoffe',
    searchTerms: ['organische peroxide', 'selbstzersetzlich', 'peroxide'],
  },
  {
    id: '6.1 A',
    label: 'LGK 6.1 A',
    shortDescription: 'BrennBetriebsanweisungre akut toxische Stoffe',
    searchTerms: ['akut toxisch brennBetriebsanweisungr', 'giftig brennBetriebsanweisungr'],
  },
  {
    id: '6.1 B',
    label: 'LGK 6.1 B',
    shortDescription: 'NichtbrennBetriebsanweisungre akut toxische Stoffe',
    searchTerms: ['akut toxisch nichtbrennBetriebsanweisungr', 'giftig nichtbrennBetriebsanweisungr'],
  },
  {
    id: '6.1 C',
    label: 'LGK 6.1 C',
    shortDescription: 'BrennBetriebsanweisungre toxische oder chronisch wirkende Stoffe',
    searchTerms: ['chronisch toxisch brennBetriebsanweisungr', 'giftig chronisch brennBetriebsanweisungr'],
  },
  {
    id: '6.1 D',
    label: 'LGK 6.1 D',
    shortDescription: 'NichtbrennBetriebsanweisungre toxische oder chronisch wirkende Stoffe',
    searchTerms: ['chronisch toxisch nichtbrennBetriebsanweisungr', 'giftig chronisch nichtbrennBetriebsanweisungr'],
  },
  {
    id: '6.2',
    label: 'LGK 6.2',
    shortDescription: 'Ansteckungsgefährliche Stoffe',
    searchTerms: ['infektiös', 'ansteckungsgefährlich', 'biologisch'],
  },
  {
    id: '7',
    label: 'LGK 7',
    shortDescription: 'Radioaktive Stoffe',
    searchTerms: ['radioaktiv', 'strahlenschutz'],
  },
  {
    id: '8 A',
    label: 'LGK 8 A',
    shortDescription: 'BrennBetriebsanweisungre ätzende Stoffe',
    searchTerms: ['ätzend brennBetriebsanweisungr', 'säuren brennBetriebsanweisungr', 'laugen brennBetriebsanweisungr'],
  },
  {
    id: '8 B',
    label: 'LGK 8 B',
    shortDescription: 'NichtbrennBetriebsanweisungre ätzende Stoffe',
    searchTerms: ['ätzend nichtbrennBetriebsanweisungr', 'säuren nichtbrennBetriebsanweisungr', 'laugen nichtbrennBetriebsanweisungr'],
  },
  {
    id: '10-13',
    label: 'LGK 10-13',
    shortDescription: 'Sonstige brennBetriebsanweisungre und nichtbrennBetriebsanweisungre Stoffe',
    searchTerms: ['sonstige stoffe', 'lagerklasse 10 bis 13'],
  },
  {
    id: '10*',
    label: 'LGK 10*',
    shortDescription: 'BrennBetriebsanweisungre Flüssigkeiten, soweit nicht LGK 3',
    searchTerms: ['brennBetriebsanweisungre flüssigkeiten', 'nicht lgk 3'],
  },
  {
    id: '11*',
    label: 'LGK 11*',
    shortDescription: 'BrennBetriebsanweisungre Feststoffe',
    searchTerms: ['brennBetriebsanweisungre feststoffe'],
  },
  {
    id: '12*',
    label: 'LGK 12*',
    shortDescription: 'NichtbrennBetriebsanweisungre Flüssigkeiten',
    searchTerms: ['nichtbrennBetriebsanweisungre flüssigkeiten'],
  },
  {
    id: '13*',
    label: 'LGK 13*',
    shortDescription: 'NichtbrennBetriebsanweisungre Feststoffe',
    searchTerms: ['nichtbrennBetriebsanweisungre feststoffe'],
  },
] as const satisfies StorageClass[];
